### ISSUE TITLE
Latest release actions are failing

### ISSUE THREAD

**Issue by mgmgwi** [boschresearch/aries-acapy-clients#11]
The release action is currently failing, see https://github.com/boschresearch/aries-acapy-clients/actions/runs/878170007

This might be related to https://github.com/mathieucarbou/license-maven-plugin/issues/206
Would you consider the proposed workaround and add `-Darguments="-Dlicense.skip=true` ? I can create an PR with this change if this helps.

Thanks,
Guido

**Comment by etschelp** [comment]
Thanks for the hint. It was already fixed in the 0.7 branch, but I merged the fix to the main branch as well.

**Comment by mgmgwi** [comment]
Great, thank you very much.
